---

- name: Installation packages
  yum:
    name:
      - httpd
      - php
      - php-mysql
    state: present

- name: restart and enable apache
  systemd:
    name: httpd
    enabled: yes
    state: restarted

- name: ouvrir port 80
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: true
    

- name: droit d'ecriture sur dossier http
  file:
   path: /var/www/html
   state: directory
   mode: 0755
   
   
- name: copie app
  copy:
    src: app/
    dest: /var/www/html
