---

- name: Installation Packages
  yum:
    name:
      - git
      - epel-release
      - httpd
      - php
      - php-mysql
    state: present

- name: reboot apach
  systemd:
    name: httpd
    enabled: yes
    state: restarted
    
- name: port 80
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: permission
  file:
   path: /var/www/html
   state: directory
   mode: 0755
# tasks file for apache
