---

- name: install mariadb package
  yum:
   name: 
    - mariadb
    - mariadb-server
   state: present

- name: restart mariadb service
  systemd:
    name: mariadb
    enabled: yes
    state: restarted

- name: Start mysql_secure_installation
  command: 'echo "& y y Mypasswd Mypasswd y y y y" | ./usr/bin/mysql_secure_installation'


# tasks file for mariadb
